server:
  port: 9191

spring:
  devtools:
    livereload:
      port: 35730
#  kafka:
#    producer:
#      bootstrap-server: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
##      properties:
##        spring:
##          json:
##            trusted:
##              packages: com.example.kafka.producer.dto.*

app:
  kafka:
    topic-name: myTopic
    partitions: 2
    replicationFactor: 1
    BootstrapSeversConfig: localhost:9092